model:
  backbone:
    type: ViT
    model_name: vit_base_patch16_224
    img_size: 224
    pretrained: false
    dino_pretrained: true
    dino_arch: vit_base
    patch_size: 16
    drop_rate: 0.0
    drop_path_rate: 0.1
    freeze_bn_stats: false
    freeze_bn_weights: false
  backbone_output_channels: 768  # ViT-Base feature dimension
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: false
        clip_scores: true
        location_refinement: true
        locref_std: 7.2801
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: 37
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        gradient_masking: true
        background_weight: 0.0
        generate_locref: true
        locref_std: 7.2801
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
        locref:
          type: WeightedHuberCriterion
          weight: 0.05
      heatmap_config:
        channels:
        - 768  # Match ViT backbone output channels
        kernel_size: []
        strides: []
        final_conv:
          out_channels: 37
          kernel_size: 1
      locref_config:
        channels:
        - 768  # Match ViT backbone output channels
        kernel_size: []
        strides: []
        final_conv:
          out_channels: 74
          kernel_size: 1
runner:
  optimizer:
    type: AdamW
    params:
      lr: 1e-4
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [ [ 5e-5 ], [ 1e-5 ] ]
      milestones: [ 90, 120 ]